FROM python:3.11-slim-bullseye
FROM pytorch/pytorch:2.0.1-cuda11.7-cudnn8-runtime

# build tools for torch/tokenizers wheels
RUN apt-get update && \
    apt-get install -y --no-install-recommends build-essential git && \
    rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY app/ ./app/

EXPOSE 8000
CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000"]
